name: Unit Test on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit -- --watchAll=false --reporters=default --reporters=jest-junit
- name: Display Test Results
  run: cat test-results.txt
