name: Unit Test on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test
    - name: Run Coverage
      run: npm run coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
